import React, { useEffect, useState } from 'react';
import { BookHeart, Plus, Save } from 'lucide-react';
import { historyService } from '../services/historyService';
import type { SongView } from '../types';

type Memory = { song: string; artist: string; note: string; date: string; mood: string; tags: string };
const key = 'moodify_memories';
export const DiaryPage: React.FC = () => {
  const [history, setHistory] = useState<SongView[]>([]);
  const [memories, setMemories] = useState<Memory[]>(() => JSON.parse(localStorage.getItem(key) || '[]') as Memory[]);
  const [selected, setSelected] = useState<SongView | null>(null);
  const [note, setNote] = useState('');
  useEffect(() => { historyService.getHistory().then(setHistory).catch(() => {}); }, []);
  const save = () => { if (!selected || !note.trim()) return; const next = [{ song: selected.title, artist: selected.artist, note, date: new Date().toISOString().slice(0, 10), mood: 'Nostalgic', tags: 'Listening memory' }, ...memories]; setMemories(next); localStorage.setItem(key, JSON.stringify(next)); setNote(''); setSelected(null); };
  return <div className="space-y-10"><header><p className="eyebrow text-[#F5C76A]">Personal music diary</p><h1 className="page-title">Your Music Timeline</h1><p className="page-copy">Keep the story around a song. Notes stay on this device in this first local experience.</p></header><section className="grid gap-5 lg:grid-cols-[1fr_0.8fr]"><div className="rounded-2xl border border-white/10 bg-[#121525] p-6"><div className="mb-6 flex items-center gap-3"><BookHeart className="h-5 w-5 text-[#F5C76A]" /><h2 className="text-xl font-bold text-white">Add a memory</h2></div>{history.length ? <div className="space-y-2">{history.slice(0, 6).map((song) => <button key={song.id} onClick={() => setSelected(song)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected?.id === song.id ? 'border-[#F5C76A]/60 bg-[#F5C76A]/10' : 'border-white/5 bg-white/[0.03]'}`}><Plus className="h-4 w-4 text-[#F5C76A]" /><span><strong className="block text-sm text-white">{song.title}</strong><small className="text-xs text-[#A9ACC1]">{song.artist}</small></span></button>)}</div> : <p className="text-sm text-[#A9ACC1]">Play a song to begin your timeline.</p>}{selected && <div className="mt-5 space-y-3"><p className="text-sm text-[#F5C76A]">Remembering: {selected.title}</p><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="What do you want to remember?" className="min-h-24 w-full rounded-xl border border-white/10 bg-[#191D31] p-3 text-sm text-white outline-none focus:border-[#F5C76A]" /><button onClick={save} className="flex items-center gap-2 rounded-full bg-[#F5C76A] px-4 py-2 text-sm font-bold text-[#0B0D17]"><Save className="h-4 w-4" /> Save memory</button></div>}</div><div><h2 className="mb-4 text-xl font-bold text-white">Listening memories</h2>{memories.length ? <div className="space-y-3">{memories.map((memory, index) => <article key={`${memory.date}-${index}`} className="rounded-2xl border border-white/10 bg-[#191D31] p-5"><p className="text-xs font-bold uppercase tracking-widest text-[#F5C76A]">{memory.date} · {memory.mood}</p><h3 className="mt-2 font-bold text-white">{memory.song}</h3><p className="mt-2 text-sm leading-6 text-[#A9ACC1]">“{memory.note}”</p><p className="mt-3 text-xs text-[#70D6D0]">{memory.tags}</p></article>)}</div> : <div className="rounded-2xl border border-dashed border-white/10 p-8 text-sm text-[#A9ACC1]">No memories yet. Your next song can become one.</div>}</div></section></div>;
};
