import React, { useEffect, useState } from 'react';
import { ArrowRight, Compass, SlidersHorizontal } from 'lucide-react';
import { songService } from '../services/songService';
import type { SongView } from '../types';
import { usePlayer } from '../hooks/usePlayer';

export const DiscoverPage: React.FC = () => {
  const [songs, setSongs] = useState<SongView[]>([]);
  const [serendipity, setSerendipity] = useState(68);
  const { playSong } = usePlayer();
  useEffect(() => { songService.getAllSongs(0, 12).then((page) => setSongs(page.content)).catch(() => setSongs([])); }, []);
  const node = (song: SongView, index: number) => <button key={song.id} onClick={() => playSong(song, songs)} className="discovery-node text-left"><div className="flex items-center gap-2"><div className="artwork h-[3.3rem] w-[3.3rem] shrink-0 rounded-full">{song.coverImageUrl ? <img src={song.coverImageUrl} alt="" /> : <div className="artwork-placeholder"><Compass className="h-4 w-4" /></div>}</div><span className="min-w-0"><strong className="block truncate text-xs text-[#EDEAF7]">{song.title}</strong><small className="block truncate text-[10px] text-[#A7ABC0]">{song.artist}</small></span></div><span className="mt-2 block text-[10px] uppercase tracking-wider text-[#8D86D9]">New to you · {index % 2 ? 'unexpected language' : 'a quieter genre'}</span></button>;
  return <div className="space-y-10"><header><p className="eyebrow">Unknown to you</p><h1 className="page-title">Discover music<br className="hidden sm:block" /> beyond your orbit.</h1><p className="page-copy">A field of unfamiliar voices, selected for contrast and connection — not arranged as another playlist grid.</p></header><section className="panel p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-[#8D86D9]">Your discovery field</p><p className="mt-2 text-sm text-[#A7ABC0]">Familiar → new → unexpected → unknown</p></div><div className="flex items-center gap-2 text-xs text-[#A7ABC0]"><SlidersHorizontal className="h-4 w-4" /> More serendipity</div></div><div className="discovery-field">{songs.slice(0, 4).map(node)}<div className="discovery-core">Find<br />unknown</div></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs font-semibold text-[#A7ABC0]"><span>COMFORT</span><span className="text-[#D9B56D]">SERENDIPITY</span></div><input aria-label="Balance comfort and serendipity" type="range" min="0" max="100" value={serendipity} onChange={(event) => setSerendipity(Number(event.target.value))} className="w-full accent-[#8D86D9]" /><p className="mt-3 text-xs text-[#737B95]">{serendipity > 70 ? 'The field is widening: more distant genres, languages, and artists.' : 'The field is staying close to your familiar musical character.'}</p></div></section><section className="grid gap-5 lg:grid-cols-[1fr_0.7fr]"><div><h2 className="section-title">Why these songs?</h2><p className="section-copy mt-2">Moodify weighs what you have played, artist familiarity, genre distance, language, geography, popularity, and diversity. The explanation is a visible rule — never a pretend AI claim.</p></div><button onClick={() => songs[0] && playSong(songs[0], songs)} className="panel-quiet panel-hover flex items-center justify-between p-5 text-left"><span><span className="block text-xs uppercase tracking-wider text-[#8D86D9]">Start at the edge</span><strong className="mt-2 block text-base text-white">Play this discovery field</strong></span><ArrowRight className="h-5 w-5 text-[#D9B56D]" /></button></section></div>;
};
