import React, { useEffect, useState } from 'react';
import { ArrowDown, Play, SlidersHorizontal } from 'lucide-react';
import { songService } from '../services/songService';
import { usePlayer } from '../hooks/usePlayer';
import type { SongView } from '../types';

export const JourneysPage: React.FC = () => {
  const [songs, setSongs] = useState<SongView[]>([]);
  const { playSong } = usePlayer();
  useEffect(() => { songService.getAllSongs(0, 12).then((page) => setSongs(page.content)).catch(() => {}); }, []);
  const stages = ['Unwind', 'Drift', 'Explore', 'Lift', 'Arrive'];
  return <div className="space-y-10"><header><p className="eyebrow text-[#FF7A73]">Sequences, not playlists</p><h1 className="page-title">Musical Journeys</h1><p className="page-copy">Let a listening session evolve from where you are to where you want to arrive.</p></header><section className="rounded-[2rem] border border-white/10 bg-[#121525] p-6 sm:p-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-[#FF7A73]">Tonight's path</p><h2 className="mt-1 text-3xl font-bold text-white">Late Night → Sunrise</h2></div><button className="flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-[#A9ACC1]"><SlidersHorizontal className="h-4 w-4" /> Shape journey</button></div><div className="my-10 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">{stages.map((stage, index) => <React.Fragment key={stage}><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#FF7A73]/50 bg-[#FF7A73]/10 text-xs font-bold text-[#FFB5B0]">{index + 1}</span><span className="text-sm font-semibold text-white">{stage}</span></div>{index < stages.length - 1 ? <ArrowDown className="ml-4 h-4 w-4 text-[#A9ACC1] sm:rotate-[-90deg]" /> : null}</React.Fragment>)}</div><button onClick={() => songs.length && playSong(songs[0], songs)} className="flex items-center gap-2 rounded-full bg-[#FF7A73] px-5 py-3 font-bold text-[#0B0D17]"><Play className="h-4 w-4 fill-current" /> Start journey</button></section><section><h2 className="mb-4 text-2xl font-bold text-white">Songs along the way</h2><div className="space-y-2">{songs.slice(0, 5).map((song, index) => <button key={song.id} onClick={() => playSong(song, songs)} className="flex w-full items-center gap-4 rounded-xl border border-white/5 bg-white/[0.03] p-3 text-left hover:border-white/15"><span className="w-6 text-center text-xs text-[#A9ACC1]">{index + 1}</span><div className="h-12 w-12 overflow-hidden rounded-lg bg-[#191D31]">{song.coverImageUrl && <img src={song.coverImageUrl} alt="" className="h-full w-full object-cover" />}</div><span className="flex-1"><strong className="block text-sm text-white">{song.title}</strong><small className="text-xs text-[#A9ACC1]">{song.artist} · {stages[index % stages.length]}</small></span><Play className="h-4 w-4 text-[#F5C76A]" /></button>)}</div></section></div>;
};
